### ISSUE TITLE
[Feature-request] Being able to serialize and deserialize a request.

### ISSUE THREAD

**Issue by Nurrl** [hyperium/http#313] opened 2019-05-18 11:34 UTC
Hello,

I found your Crate very useful, tho, in my opinion, there is a problem with it, we can't serialize and deserialize the `http::Request` and `http::Response` objects, but it would be very handy !
I thought about something like this:
```rust
let request = Request::get("https://google.fr")
    .body(());

let rawrequest = request.as_raw();
/* rawrequest content:
 * GET https://google.fr HTTP/1.1\r\n
 * \r\n
 */
```
and
```rust
let rawresponse = r#"
HTTP/1.1 200 OK\r\n
Connection: Closed\r\n
...
\r\n
<Google Content>
"#
let response = Response::from_raw(rawresponse);
```

This would permit very low-performance-cost http requests over `UnixStream` and `TcpStream` !

**Comment by seanmonstar** [comment] 2019-05-18 15:23
Thanks for the request! However, this is a duplicate of one that already explains why it feels out of scope for this crate: https://github.com/hyperium/http/issues/81

**Closed by seanmonstar** 2019-05-18 15:23 UTC
