### ISSUE TITLE
X-<Header> converts to lowercase

### ISSUE THREAD

**Issue by crusty-dave** [hyperium/http#228] opened 2018-07-14 03:54 UTC
With the following code:

`Ok(HttpResponse::Ok() .header("X-Subject-Token", token.token) .body(""))`

It transmits "X-Subject-Token" as "x-subject-token", this would seem to be a bug, it shouldn't be changing any header tags like this AFAIK?

Per RFC 7230, the headers should be case-insensitive, but I would still expect http to honor the case that I have provided.

[RFC 7230](https://tools.ietf.org/html/rfc7230#page-19)

> 3.2. Header Fields
> 
> Each header field consists of a case-insensitive field name followed
> by a colon (":"), optional leading whitespace, the field value, and
> optional trailing whitespace.
> 

Note that the HTTP RFCs use camel-case with dash (-) separators when they describe the fields.

This is the first time that I have witnessed something like "content-type" instead of "Content-Type".

I would think that this might cause some compatibility issues with some http processors if they ignored section 3.2 (I ran into some code with that issue).  So at the least, there should be an option to preserve Camel-Case if present IMO.

**Comment by carllerche** [comment] 2018-07-14 04:02
Thanks for the report.

The HTTP crate internally normalizes to lower case in order to implement a number of performance optimizations. As you quoted, the spec defines HTTP header fields as being case-insensitive.

The `http` crate has no plans to add support for maintaining header name case as this would introduce a performance regression for all users.

It is possible for HTTP client and server implementations to add features supporting invalid HTTP peers without the `http` crate doing anything. If you hit a real interopt problem, I would suggest opening an issue with the client / server you are using.

I'm going to close this issue as there is no further action for us to take.

**Comment by seanmonstar** [comment] 2018-07-14 04:02
As you've pointed out, RFC 7230 says names are case-insensitive, so *should* be perfectly valid to treat `X-Subject-Token` as `x-subject-token`. Additionally, in HTTP/2, **all** header names are lowercase (it's specified to be a protocol error for upper case names). Because of this, `HeaderName` chooses to always handle names as lower case. Doing this allows optimizations: case-insensitive hashing and comparison are no longer required, improving speed of inserts and searches in the `HeaderMap`.

Notably, `HeaderName` is just an optimized holder of a header name string. HTTP implementations certainly can transform the name bytes to camel case before serializing to a network stream, For example, [hyper provides an option to do just that](https://docs.rs/hyper/0.12.*/hyper/client/struct.Builder.html#method.http1_title_case_headers), for when users actually do have to deal with bad HTTP implementations. In hyper, it isn't enabled by default, since there's a cost to transforming the bytes, and most HTTP implementations are good-ish, and handle header names correctly.

You could ask actix-web to provide such an option.

**Closed by carllerche** 2018-07-14 04:02 UTC
